### ISSUE TITLE
Drag for multiple words

### ISSUE THREAD

**Issue by jjblodgett** [dougbenham/CtrlClick#1]
One thing I noticed right away is that it works great with single words but if I need to do a phrase, I don't see a way to CTRL+click and drag to select multiple words. Any chance that's an easy adjustment or am I missing a way to do that currently?

**Comment by legier** [comment]
I fixed that in this pull request: https://github.com/dougbenham/CtrlClick/pull/3

**Comment by dougbenham** [comment]
New release is added with @legier's fix.

**Comment by jjblodgett** [comment]
I don't work with CPP so didn't even think to look at the code. But mouseDown vs mouseUp makes perfect sense why it wasn't doing it! Thanks @legier and @dougbenham.
