### ISSUE TITLE
Unable to use the native "CTRL+drag to copy" in VS Code now (and probably others IDE)

### ISSUE THREAD

**Issue by jjblodgett** [dougbenham/CtrlClick#2]
Just came across another issue as it seems that the intercept is blocking a feature that is available in VS Code and others.  If I want to copy section of code in my document, I can normally select the text, hold CTRL, and then drag to the desired location and it creates a copy of the test. Unfortunately, I'm guessing the double-click is actually happening when I try to click and drag so it's not creating the copy. So not sure if there's even something that can be done about that. I can still "move" test from one place to another if I don't hold down CTRL but I lose the ability to copy.

**Comment by legier** [comment]
After selection, just first start dragging, then press CTRL (this sequence will not trigger the hook).

**Comment by dougbenham** [comment]
@legier's workaround seems pretty reasonable and works for me.

**Comment by jjblodgett** [comment]
I usually do that in the other order (hold CTRL and then drag) but it does seem to work if I drag and then CTRL. I'm more than happy to re-train myself to do that in a different order if I gain the ability to CTRL + CLICK so I think that's reasonable enough for now. :)  Thanks!
